### PR TITLE
fix(reload_sessions): fixed sessions reloading bug, if there is only …

### PR DESCRIPTION
**Pull request by RobinRuf**
…one session left after deleting

If there is just one session left right after deleting another, an ugly error message appears and the remaining session will not reload properly without reopening sessionx. (Tested on OSX Sonoma 14.1.1)

Screenshot 2023-12-30 at 14 55 51

### CODE REVIEW

**Comment by RobinRuf** [comment]
Sorry, I do not really understand, why it shows that many changes in sessionx.sh, I just changed 1 line and added the reload_sessions.sh file.

```shell
- BIND_ALT_BSPACE="alt-bspace:execute(tmux kill-session -t {})+reload(tmux list-sessions | sed -E 's/:.*$//' | grep -v $(tmux display-message -p '#S'))"
+ BIND_ALT_BSPACE="alt-bspace:execute-silent(tmux kill-session -t {})+reload(${TMUX_PLUGIN_MANAGER_PATH%/}/tmux-sessionx/scripts/reload_sessions.sh)"
```

**Comment by omerxx** [comment]
Thanks! Looking into it

**Comment by omerxx** [comment]
@RobinRuf That's great, I'd love to merge if you could eliminate the formatting changes, otherwise I'll manually cherry pick the changes

**Comment by RobinRuf** [comment]
@omerxx I just wrote you an email, would be nice If you can look at it and maybe reply shortly. It is because of these indent/formatting changes.

Also, I think it would be better if I pull the main again later and do the changes there, because now it would have a conflict because of the latest merge.
I can do it right after a reply of my mail, because these formatting changes are confusing.

**Comment by RobinRuf** [comment]
I synced my fork with the latest version of the main branch (because of the latest merge a few hours ago)

I did the same thing without formatting changes and for the latest version in #28 , so please take a look and then you can merge it :)

**Pull request closed without merging**
