### PR TITLE
Yet another faster popup

### PR DESCRIPTION
**Pull request by Marat-Gumerov**

### CODE REVIEW

**Comment by Marat-Gumerov** [comment]
Well, now I see that it breaks previews :)

**Comment by Marat-Gumerov** [comment]
Fixed the preview

**Comment by Marat-Gumerov** [comment]
Fixed tmuxinator

**Comment by omerxx** [comment]
Hey @Marat-Gumerov this looks great, going to test it tomorrow.
Have you had the chance to run some performance tests to see the difference?

**Comment by Marat-Gumerov** [comment]
> Hey @Marat-Gumerov this looks great, going to test it tomorrow. Have you had the chance to run some performance tests to see the difference?

For some reason, it now takes only 150 ms to open my popup. I think it was around 215 ms three weeks ago.

Anyway, I have been using this version for three weeks now, and I'm happy with the performance.

I use tmuxinator in my workflow, but I have never tested fzf-marks. I don't even know what it is. So I hope you can test it.

**Comment by Marat-Gumerov** [comment]
<details><summary>One of my latest tests:</summary>
<p>

133 ms from start to fzf-tmux call:

```shell
~/.config/tmux/plugins/tmux-sessionx$ PS4='+ $(date "+%s.%N")\011 ' bash -x scripts/sessionx.sh
+++ 1732267263.210858207         dirname scripts/sessionx.sh
++ 1732267263.216733547  cd scripts
++ 1732267263.220916627  pwd
+ 1732267263.225551354   CURRENT_DIR=/home/mt/.config/tmux/plugins/tmux-sessionx/scripts
++ 1732267263.230547010  tmux display-message -p '#S'
+ 1732267263.241551019   CURRENT=apps
+ 1732267263.243370015   Z_MODE=off
+ 1732267263.244792038   source /home/mt/.config/tmux/plugins/tmux-sessionx/scripts/tmuxinator.sh
+ 1732267263.246709733   source /home/mt/.config/tmux/plugins/tmux-sessionx/scripts/fzf-marks.sh
+ 1732267263.248414813   run_plugin
++ 1732267263.249843227  tmux show-option -gqv @sessionx-_built-args
+ 1732267263.257139575   eval declare -a 'args=([0]="--bind"' '[1]="ctrl-t:change-preview(/home/mt/.config/tmux/plugins/tmux-sessionx/scripts/preview.sh' -t '{1})"' '[2]="--bind"' '[3]="ctrl-x:reload(find' /home/mt/.config -mindepth 1 -maxdepth 1 -type d -o -type 'l)+change-preview(ls' '{})"' '[4]="--bind"' '[5]="ctrl-w:reload(tmux' list-windows -a -F ''\''#{session_name}:#{window_name}'\'')+change-preview(/home/mt/.config/tmux/plugins/tmux-sessionx/scripts/preview.sh' -w '{1})"' '[6]="--bind"' '[7]="ctrl-e:reload(find' /home/mt/dev/apps/aspose.email.web/src/Aspose.Email.Web.Ui/NgStatic -mindepth 1 -maxdepth 1 -type d -o -type 'l)+change-preview(ls' '{})"' '[8]="--bind"' '[9]="ctrl-f:reload(zoxide' query '-l)+change-preview(ls' '{})"' '[10]="--bind"' '[11]="alt-bspace:execute-silent(tmux' kill-session -t '{})+reload(/home/mt/.config/tmux/plugins/tmux-sessionx/scripts/reload_sessions.sh)"' '[12]="--bind"' '[13]="bspace:backward-delete-char"' '[14]="--bind"' '[15]="esc:abort"' '[16]="--bind"' '[17]="ctrl-n:up"' '[18]="--bind"' '[19]="ctrl-p:down"' '[20]="--bind"' '[21]="enter:replace-query+print-query"' '[22]="--bind"' '[23]="ctrl-u:preview-half-page-up"' '[24]="--bind"' '[25]="ctrl-d:preview-half-page-down"' '[26]="--bind"' '[27]="ctrl-r:execute(bash' -c \' printf '>&2' '\"New' name: '\";read' 'name;' tmux rename-session -t '{1}' '\"\${name}\";' ''\'')+reload(bash' -c \' tmux list-sessions '|' sed -E '\"s/:.*\$//\";' ''\'')"' '[28]="--bind"' '[29]="?:toggle-preview"' '[30]="--bind"' '[31]="change:first"' '[32]="--exit-0"' '[33]="--header=enter=󰿄'  alt-bspace=󱂧  ctrl-r=󰑕  ctrl-x=󱃖  ctrl-w=  ctrl-e=󰇘  ctrl-b=󰌍  ctrl-t=󰐆  ctrl-u=  ctrl-d= / 'ctrl-f="' '[34]="--preview=/home/mt/.config/tmux/plugins/tmux-sessionx/scripts/preview.sh' '{}"' '[35]="--preview-window=top,75%,,"' '[36]="--layout=default"' '[37]="--pointer=▶"' '[38]="-p"' '[39]="75%,75%"' '[40]="--prompt"' '[41]="' '"' '[42]="--print-query"' '[43]="--tac"' '[44]="--scrollbar"' '[45]="▌▐"' '[46]="--border-label"' '[47]="Current' session: '\"\"' '"' '[48]="--bind"' '[49]="focus:transform-preview-label:echo' '[' '{}' ']"' '[50]="--bind"' '[51]="F1:reload(tmuxinator' list --newline '|' sed ''\''1d'\'')+change-preview(cat' '~/.config/tmuxinator/{}.yml' '2>/dev/null)")'
++ 1732267263.258618989  args=(['0']='--bind' ['1']='ctrl-t:change-preview(/home/mt/.config/tmux/plugins/tmux-sessionx/scripts/preview.sh -t {1})' ['2']='--bind' ['3']='ctrl-x:reload(find /home/mt/.config -mindepth 1 -maxdepth 1 -type d -o -type l)+change-preview(ls {})' ['4']='--bind' ['5']='ctrl-w:reload(tmux list-windows -a -F '\''#{session_name}:#{window_name}'\'')+change-preview(/home/mt/.config/tmux/plugins/tmux-sessionx/scripts/preview.sh -w {1})' ['6']='--bind' ['7']='ctrl-e:reload(find /home/mt/dev/apps/aspose.email.web/src/Aspose.Email.Web.Ui/NgStatic -mindepth 1 -maxdepth 1 -type d -o -type l)+change-preview(ls {})' ['8']='--bind' ['9']='ctrl-f:reload(zoxide query -l)+change-preview(ls {})' ['10']='--bind' ['11']='alt-bspace:execute-silent(tmux kill-session -t {})+reload(/home/mt/.config/tmux/plugins/tmux-sessionx/scripts/reload_sessions.sh)' ['12']='--bind' ['13']='bspace:backward-delete-char' ['14']='--bind' ['15']='esc:abort' ['16']='--bind' ['17']='ctrl-n:up' ['18']='--bind' ['19']='ctrl-p:down' ['20']='--bind' ['21']='enter:replace-query+print-query' ['22']='--bind' ['23']='ctrl-u:preview-half-page-up' ['24']='--bind' ['25']='ctrl-d:preview-half-page-down' ['26']='--bind' ['27']='ctrl-r:execute(bash -c '\'' printf >&2 "New name: ";read name; tmux rename-session -t {1} "${name}"; '\'')+reload(bash -c '\'' tmux list-sessions | sed -E "s/:.*$//"; '\'')' ['28']='--bind' ['29']='?:toggle-preview' ['30']='--bind' ['31']='change:first' ['32']='--exit-0' ['33']='--header=enter=󰿄  alt-bspace=󱂧  ctrl-r=󰑕  ctrl-x=󱃖  ctrl-w=  ctrl-e=󰇘  ctrl-b=󰌍  ctrl-t=󰐆  ctrl-u=  ctrl-d= / ctrl-f=' ['34']='--preview=/home/mt/.config/tmux/plugins/tmux-sessionx/scripts/preview.sh {}' ['35']='--preview-window=top,75%,,' ['36']='--layout=default' ['37']='--pointer=▶' ['38']='-p' ['39']='75%,75%' ['40']='--prompt' ['41']=' ' ['42']='--print-query' ['43']='--tac' ['44']='--scrollbar' ['45']='▌▐' ['46']='--border-label' ['47']='Current session: "" ' ['48']='--bind' ['49']='focus:transform-preview-label:echo [ {} ]' ['50']='--bind' ['51']='F1:reload(tmuxinator list --newline | sed '\''1d'\'')+change-preview(cat ~/.config/tmuxinator/{}.yml 2>/dev/null)')
++ 1732267263.260053853  declare -a args
++ 1732267263.261525828  tmux show-option -gqv @sessionx-_built-extra-options
+ 1732267263.266802921   eval declare -A 'extra_options=([custom-paths-subdirectories]="false"' '[filtered-sessions]=""' '[bind-back]="ctrl-b"' '[custom-paths]=""' '[filter-current]="true"' '[window-mode]="off"' ')'
++ 1732267263.267889182  extra_options=(['custom-paths-subdirectories']='false' ['filtered-sessions']='' ['bind-back']='ctrl-b' ['custom-paths']='' ['filter-current']='true' ['window-mode']='off')
++ 1732267263.269424133  declare -A extra_options
+ 1732267263.272411928   handle_input
++ 1732267263.274127665  input
++ 1732267263.275196209  default_window_mode=off
++ 1732267263.276166494  [[ off == \o\n ]]
++ 1732267263.277264228  filter_current_session=true
++ 1732267263.278399880  [[ true == \t\r\u\e ]]
++ 1732267263.280535997  get_sorted_sessions
++ 1732267263.280567867  grep -v 'apps$'
+++ 1732267263.281881419         tmux display-message -p '#{client_last_session}'
++ 1732267263.285702884  last_session=tasks
+++ 1732267263.289409998         tmux list-sessions
+++ 1732267263.289466139         sed -E 's/:.*$//'
+++ 1732267263.289773856         grep -v '^tasks$'
++ 1732267263.294629166  sessions='apps
config
ez
lp'
++ 1732267263.296489726  filtered_sessios=
++ 1732267263.297845224  [[ -n '' ]]
++ 1732267263.299094983  echo -e 'apps
config
ez
lp\ntasks'
++ 1732267263.299196929  awk '!seen[$0]++'
+ 1732267263.302337456   INPUT='config
ez
lp
tasks'
++ 1732267263.305294847  additional_input
+++ 1732267263.306660899         get_sorted_sessions
++++ 1732267263.308000497        tmux display-message -p '#{client_last_session}'
+++ 1732267263.313577481         last_session=tasks
++++ 1732267263.315150514        tmux list-sessions
++++ 1732267263.315276938        sed -E 's/:.*$//'
++++ 1732267263.315366564        grep -v '^tasks$'
+++ 1732267263.320609669         sessions='apps
config
ez
lp'
+++ 1732267263.322278870         filtered_sessios=
+++ 1732267263.323330249         [[ -n '' ]]
+++ 1732267263.324605569         echo -e 'apps
config
ez
lp\ntasks'
+++ 1732267263.324657299         awk '!seen[$0]++'
++ 1732267263.327864975  sessions='apps
config
ez
lp
tasks'
++ 1732267263.330235626  custom_paths=
++ 1732267263.331638700  custom_path_subdirectories=false
++ 1732267263.332722908  [[ -z '' ]]
++ 1732267263.333718642  echo ''
+ 1732267263.334959030   ADDITIONAL_INPUT=
+ 1732267263.336269772   [[ -n '' ]]
+ 1732267263.338224471   bind_back=ctrl-b
+ 1732267263.339383378   BACK='ctrl-b:reload(echo -e "config
ez
lp
tasks")+change-preview(/home/mt/.config/tmux/plugins/tmux-sessionx/scripts/preview.sh {1})'
+ 1732267263.340439394   args+=(--bind "$BACK")
+ 1732267263.341484272   [[ '' == \o\n ]]
++ 1732267263.343156919  echo -e 'config
ez
lp
tasks'
++ 1732267263.343359786  sed -E 's/✗/ /g'
++ 1732267263.343402567  tail -n1
++ 1732267263.343508067  fzf-tmux --bind 'ctrl-t:change-preview(/home/mt/.config/tmux/plugins/tmux-sessionx/scripts/preview.sh -t {1})' --bind 'ctrl-x:reload(find /home/mt/.config -mindepth 1 -maxdepth 1 -type d -o -type l)+change-preview(ls {})' --bind 'ctrl-w:reload(tmux list-windows -a -F '\''#{session_name}:#{window_name}'\'')+change-preview(/home/mt/.config/tmux/plugins/tmux-sessionx/scripts/preview.sh -w {1})' --bind 'ctrl-e:reload(find /home/mt/dev/apps/aspose.email.web/src/Aspose.Email.Web.Ui/NgStatic -mindepth 1 -maxdepth 1 -type d -o -type l)+change-preview(ls {})' --bind 'ctrl-f:reload(zoxide query -l)+change-preview(ls {})' --bind 'alt-bspace:execute-silent(tmux kill-session -t {})+reload(/home/mt/.config/tmux/plugins/tmux-sessionx/scripts/reload_sessions.sh)' --bind bspace:backward-delete-char --bind esc:abort --bind ctrl-n:up --bind ctrl-p:down --bind enter:replace-query+print-query --bind ctrl-u:preview-half-page-up --bind ctrl-d:preview-half-page-down --bind 'ctrl-r:execute(bash -c '\'' printf >&2 "New name: ";read name; tmux rename-session -t {1} "${name}"; '\'')+reload(bash -c '\'' tmux list-sessions | sed -E "s/:.*$//"; '\'')' --bind '?:toggle-preview' --bind change:first --exit-0 '--header=enter=󰿄  alt-bspace=󱂧  ctrl-r=󰑕  ctrl-x=󱃖  ctrl-w=  ctrl-e=󰇘  ctrl-b=󰌍  ctrl-t=󰐆  ctrl-u=  ctrl-d= / ctrl-f=' '--preview=/home/mt/.config/tmux/plugins/tmux-sessionx/scripts/preview.sh {}' --preview-window=top,75%,, --layout=default --pointer=▶ -p 75%,75% --prompt ' ' --print-query --tac --scrollbar ▌▐ --border-label 'Current session: "" ' --bind 'focus:transform-preview-label:echo [ {} ]' --bind 'F1:reload(tmuxinator list --newline | sed '\''1d'\'')+change-preview(cat ~/.config/tmuxinator/{}.yml 2>/dev/null)' --bind 'ctrl-b:reload(echo -e "config
ez
lp
tasks")+change-preview(/home/mt/.config/tmux/plugins/tmux-sessionx/scripts/preview.sh {1})'
+ 1732267264.601375381   RESULT=
+ 1732267264.606075807   handle_output ''
+ 1732267264.610751736   '[' -d '' ']'
+ 1732267264.616071965   is_fzf-marks_mark ''
++ 1732267264.624945598  echo ''
++ 1732267264.625581632  grep -q ' : '
+ 1732267264.632015533   return 1
+ 1732267264.636092120   echo ''
+ 1732267264.636154018   grep :
++ 1732267264.642151689  tr -d '\n'
++ 1732267264.642184777  echo ''
+ 1732267264.648179236   target=
+ 1732267264.650130157   [[ -z '' ]]
+ 1732267264.651685896   exit 0

``` 

</p>
</details>

**Comment by omerxx** [comment]
Looks great. I'll give it a go myself and update.

**Pull request merged**
