### PR TITLE
stops removing spaces from session names

### LINKED ISSUE #38: sessionx doesn't work with session names that have spaces
If I rename my session to a name with a space, sessionx returns an invalid session.

For example, if I name my session `some session name`, the session will appear as `somesessionname` in sessionx with the error `Unknown session: somesessionname`.
Screenshot 2024-01-24 at 9 05 39 PM

### PR DESCRIPTION
**Pull request by yakloinsteak**
- Git log research: I think the space removal came about in a commit with the message "additional input for custom paths" and effectively has been in place since that feature was added. Commit: 5107ae06e0a175d68816ff081cc186214306c064

- I think the intent was to remove spaces because of a bug in additional_input. It didn't iterate over the list of options and the for loop ran once no matter what (for me at least).

I'm wondering why the additional_input method was so complicated, so maybe I'm missing something.

Fixes #38

### CODE REVIEW

**Comment by ProgmRuanSilva** [comment]
Hi @yakloinsteak thanks for contribute

I spent some time looking at this pull, but I couldn't find the error yet.

But I'll take a better look later.

**Comment by ProgmRuanSilva** [comment]
Okay, if I understand correctly what you want to do

- The Unknown session "custom-path-name" is rendered by the preview, not in additional input

We need to think of a way to get the custom path with a predefined name for it

**Comment by yakloinsteak** [comment]
I'm not sure I 100% follow, but I just pushed a commit that now lets us rename sessions with spaces. I was originally just making the sessions that already had a space in the name show up correctly (I happened to have a session called "query opt" when I installed your plugin, and it was listed as "queryopt" and I couldn't switch to it.

How does this look now? And thanks for the great plugin. It's been a great improvement to my workflow.

**Comment by ProgmRuanSilva** [comment]
> I'm not sure I 100% follow, but I just pushed a commit that now lets us rename sessions with spaces. I was originally just making the sessions that already had a space in the name show up correctly (I happened to have a session called "query opt" when I installed your plugin, and it was listed as "queryopt" and I couldn't switch to it.
> 
> How does this look now? And thanks for the great plugin. It's been a great improvement to my workflow.

Understood

like this: 
image

Okay, this is cool thanks for contributing @yakloinsteak 

Can you solve the conflict to merge it?

**Comment by yakloinsteak** [comment]
@ProgmRuanSilva I fixed the merge conflict and retested things.

**Pull request merged**
